spring.application.name=asset_management_application

spring.datasource.url=jdbc:h2:mem:asset-management-app
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
